name: Tranga
options:
  bundleIdPrefix: com.andrewgonzalez
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages:
  TaigaClient:
    path: .
targets:
  Tranga:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources/TaigaApp
    resources:
      - Sources/TaigaApp/Assets.xcassets
    info:
      path: Sources/TaigaApp/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        # GitHub OAuth URL Scheme
        CFBundleURLTypes:
          - CFBundleURLName: com.andrewgonzalez.tranga
            CFBundleURLSchemes:
              - taiga
    dependencies:
      - package: TaigaClient
        product: TaigaUI
      - package: TaigaClient
        product: TaigaCore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andrewgonzalez.tranga
        DEVELOPMENT_TEAM: U9H69CCE8H
        CODE_SIGN_STYLE: Automatic
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
schemes:
  Tranga:
    build:
      targets:
        Tranga: all
    run:
      config: Debug
